Created login page and organized project files
Hu3diger/digital-park-web pull request #2
Opened 2020-12-02 01:24 UTC by Hu3diger

2020-12-02 01:46 UTC, Viserion77 requested changes
- I ran the pr on site, and it's not 100% like the prototype, are you still going to remodel or are you going to stay anyway?
- Add the editor folder to gitignore

2020-12-02 01:46 UTC, Viserion77 commented on .vscode/settings.json
> +}}
Do you want to commit this file?

2020-12-02 23:17 UTC, Hu3diger commented on .vscode/settings.json
> +}}
Yup

2020-12-03 00:20 UTC, Viserion77 approved these changes

2020-12-03 00:20 UTC, merged